# Generated by Django 4.2.11 on 2026-05-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide this category from customers (only visible to admins)', verbose_name='hidden'),
        ),
    ]
