# Generated by Django 4.2.11 on 2026-05-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_analytics_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='idx_categories_hidden_active',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_status_created',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_flags',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='idx_reviews_rating_approved',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='idx_variants_stock_price',
        ),
    ]
