# Generated by Django 4.2.11 on 2026-05-30 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_idx_categories_hidden_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Wholesale cost - never exposed to customers', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost price'),
        ),
    ]
