# Generated by Django 4.2.11 on 2026-06-04 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_add_created_by_field'),
        ('products', '0005_productvariant_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveIntegerField(choices=[(1, '1 Star - Very Poor'), (2, '2 Stars - Poor'), (3, '3 Stars - Average'), (4, '4 Stars - Good'), (5, '5 Stars - Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='overall rating')),
                ('shipping_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Very Poor'), (2, '2 Stars - Poor'), (3, '3 Stars - Average'), (4, '4 Stars - Good'), (5, '5 Stars - Excellent')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='shipping rating')),
                ('packaging_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Very Poor'), (2, '2 Stars - Poor'), (3, '3 Stars - Average'), (4, '4 Stars - Good'), (5, '5 Stars - Excellent')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='packaging rating')),
                ('delivery_speed_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Very Poor'), (2, '2 Stars - Poor'), (3, '3 Stars - Average'), (4, '4 Stars - Good'), (5, '5 Stars - Excellent')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='delivery speed rating')),
                ('customer_service_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star - Very Poor'), (2, '2 Stars - Poor'), (3, '3 Stars - Average'), (4, '4 Stars - Good'), (5, '5 Stars - Excellent')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='customer service rating')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='review title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs from the review', verbose_name='review images')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('helpful_yes', models.PositiveIntegerField(default=0, verbose_name='helpful yes votes')),
                ('helpful_no', models.PositiveIntegerField(default=0, verbose_name='helpful no votes')),
                ('admin_response', models.TextField(blank=True, verbose_name='admin response')),
                ('admin_response_at', models.DateTimeField(blank=True, null=True, verbose_name='admin response at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order review',
                'verbose_name_plural': 'order reviews',
                'db_table': 'order_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReviewHelpful',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField(default=True, verbose_name='is helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='products.productreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product review helpful vote',
                'verbose_name_plural': 'product review helpful votes',
                'db_table': 'product_review_helpful',
            },
        ),
        migrations.CreateModel(
            name='OrderReviewHelpful',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField(default=True, verbose_name='is helpful')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='products.orderreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_review_helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order review helpful vote',
                'verbose_name_plural': 'order review helpful votes',
                'db_table': 'order_review_helpful',
            },
        ),
        migrations.AddConstraint(
            model_name='productreviewhelpful',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='unique_product_review_helpful_vote'),
        ),
        migrations.AddConstraint(
            model_name='orderreviewhelpful',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='unique_order_review_helpful_vote'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['order', 'is_approved'], name='order_revie_order_i_d68960_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['user', 'created_at'], name='order_revie_user_id_688869_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['overall_rating'], name='order_revie_overall_ed667d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreview',
            index=models.Index(fields=['created_at'], name='order_revie_created_df4444_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderreview',
            constraint=models.UniqueConstraint(fields=('order', 'user'), name='unique_order_review'),
        ),
    ]
