# Generated by Django 4.2.11 on 2026-06-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_orderreview_productreviewhelpful_orderreviewhelpful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
