# Generated by Django 4.2.11 on 2026-05-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Online Payment'), ('pod', 'Pay on Delivery')], default='online', max_length=20, verbose_name='payment type'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pod_eligible',
            field=models.BooleanField(default=False, verbose_name='pay on delivery eligible'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pod_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='POD ineligible reason'),
        ),
    ]
