# Generated by Django 4.2.11 on 2026-05-22 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_remove_orderitem_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='shipped', max_length=20, verbose_name='status')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='tracking number')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='carrier')),
                ('tracking_url', models.URLField(blank=True, verbose_name='tracking URL')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='weight (kg)')),
                ('shipped_at', models.DateTimeField(auto_now_add=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shipment',
                'verbose_name_plural': 'shipments',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20, verbose_name='status')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_updates', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='orders.shipment')),
            ],
            options={
                'verbose_name': 'shipment tracking',
                'verbose_name_plural': 'shipment tracking',
                'db_table': 'shipment_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund'), ('authorization', 'Authorization'), ('shipping', 'Shipping')], max_length=20, verbose_name='transaction type')),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='transaction ID')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='payment method')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='card last 4')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='card brand')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('refund_reason', models.TextField(blank=True, verbose_name='refund reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('receipt_url', models.URLField(blank=True, max_length=500, verbose_name='receipt URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.transaction')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'), models.Index(fields=['reference'], name='transaction_referen_c33c6b_idx'), models.Index(fields=['order', 'status'], name='transaction_order_i_8ba8dd_idx'), models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order', 'status'], name='shipments_order_i_1ac412_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipments_trackin_cc256d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['carrier'], name='shipments_carrier_428e44_idx'),
        ),
    ]
