# Generated by Django 4.2.11 on 2026-05-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shipment_shipmenttracking_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tracking number'),
        ),
    ]
