# Generated by Django 4.2.11 on 2026-05-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
    ]
