# Generated by Django 4.2.11 on 2026-05-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='carrier'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True, default='', verbose_name='tracking URL'),
        ),
    ]
