# Generated by Django 4.2.11 on 2026-05-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_shipment_carrier_alter_shipment_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='bundle discount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bundle_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bundle ID'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bundle_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='bundle name'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_bundle_item',
            field=models.BooleanField(default=False, verbose_name='is bundle item'),
        ),
    ]
