# Generated by Django 4.2.11 on 2026-07-04 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customerprofile_date_of_birth'),
        ('orders', '0011_set_order_currency_default_to_ghs'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_orders', to='users.affiliate', verbose_name='affiliate'),
        ),
        migrations.AddField(
            model_name='order',
            name='affiliate_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='affiliate commission amount'),
        ),
    ]
