# Generated by Django 4.2.11 on 2026-07-04 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_affiliate_order_affiliate_commission_amount'),
        ('promotions', '0002_discountcode_affiliatecommission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.discountcode', verbose_name='discount code'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_code_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='discount code text'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['discount_code_text'], name='orders_discoun_f2fb72_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['affiliate'], name='orders_affilia_687af6_idx'),
        ),
    ]
