# Generated by Django 4.2.11 on 2026-07-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_discount_code_order_discount_code_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="entered_discount_code_text",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="entered discount code text",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["entered_discount_code_text"],
                name="orders_entered_f5d489_idx",
            ),
        ),
    ]
