# Generated by Django 4.2.11 on 2026-07-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_entered_discount_code_text'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_entered_bcc159_idx',
            old_name='orders_entered_f5d489_idx',
        ),
    ]
