# Generated by Django 4.2.11 on 2026-07-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_orders_entered_f5d489_idx_orders_entered_bcc159_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(default=False, verbose_name='in-store pickup'),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processing at'),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_for_shipping_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ready for shipping at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_for_shipping', 'Ready for Shipping'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='status'),
        ),
    ]
