# Generated by Django 4.2.11 on 2026-07-10 16:45

import apps.orders.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_relax_orphan_orders_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('use_carrier_rates', models.BooleanField(default=True, verbose_name='use carrier rates')),
                ('free_shipping_all', models.BooleanField(default=False, verbose_name='free shipping for all')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='free shipping threshold')),
                ('pickup_enabled', models.BooleanField(default=False, verbose_name='in-store pickup enabled')),
                ('handling_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='handling fee')),
                ('max_shipping_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='max shipping cap')),
                ('fallback_surcharge_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='fallback surcharge percent')),
                ('allowed_countries', models.JSONField(blank=True, default=list, verbose_name='allowed countries')),
                ('fallback_rates', models.JSONField(default=apps.orders.models.default_fallback_rates, verbose_name='fallback rates')),
                ('shipping_methods', models.JSONField(default=apps.orders.models.default_shipping_methods, verbose_name='shipping methods')),
                ('popular_addresses', models.JSONField(blank=True, default=list, verbose_name='popular addresses')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'shipping config',
                'verbose_name_plural': 'shipping config',
                'db_table': 'shipping_config',
            },
        ),
    ]
