# Generated by Django 4.2.11 on 2026-05-15 20:54

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_address_line_1_address_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2013, 5, 15), message='Must be at least 13 years old.')], verbose_name='date of birth'),
        ),
    ]
