# Generated by Django 4.2.11 on 2026-05-19 14:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2013, 5, 19), message='Must be at least 13 years old.')], verbose_name='date of birth'),
        ),
    ]
