"""
Blog Post Schemas — validation and serialization.
Pure functions, no DB writes.
"""

from typing import Dict, Any, Tuple, Optional, List

from apps.blog.models import BlogPost, BlogCategory


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _is_blank(value: Any) -> bool:
    return value is None or (isinstance(value, str) and value.strip() == "")


def validate_post(
    data: Dict[str, Any], is_update: bool = False
) -> Tuple[Optional[Dict], Optional[Dict]]:
    """Validate blog post create/update data.  Returns (cleaned, errors)."""
    errors: Dict[str, str] = {}
    cleaned: Dict[str, Any] = {}

    # -- title --
    if "title" in data or not is_update:
        title = str(data.get("title", "") or "").strip()
        if not title:
            errors["title"] = "This field is required"
        elif len(title) > 200:
            errors["title"] = "Cannot exceed 200 characters"
        else:
            cleaned["title"] = title

    # -- content --
    if "content" in data or not is_update:
        content = str(data.get("content", "") or "").strip()
        if not content:
            errors["content"] = "This field is required"
        else:
            cleaned["content"] = content

    # -- slug (optional; auto-generated by service when absent) --
    if "slug" in data and data["slug"] is not None:
        slug = str(data["slug"]).strip()
        if slug:
            if len(slug) > 220:
                errors["slug"] = "Cannot exceed 220 characters"
            else:
                cleaned["slug"] = slug

    # -- excerpt --
    if "excerpt" in data:
        excerpt = str(data.get("excerpt", "") or "").strip()
        cleaned["excerpt"] = excerpt[:300] if excerpt else ""

    # -- cover_image_url --
    if "cover_image_url" in data:
        cleaned["cover_image_url"] = str(data.get("cover_image_url", "") or "")[:500]

    # -- category_id --
    if "category_id" in data:
        cat_id = data["category_id"]
        if cat_id is None or (isinstance(cat_id, str) and cat_id.strip() in ("", "null", "none")):
            cleaned["category_id"] = None
        else:
            from django.core.exceptions import ValidationError

            try:
                BlogCategory.objects.get(id=cat_id)
            except (BlogCategory.DoesNotExist, ValueError, ValidationError):
                errors["category_id"] = "Category not found"
            else:
                cleaned["category_id"] = cat_id

    # -- authorship --
    author_user_id = data.get("author_user_id")
    author_name = str(data.get("author_name", "") or "").strip()

    if "author_user_id" in data:
        if author_user_id is None or (isinstance(author_user_id, str) and author_user_id.strip() in ("", "null", "none")):
            cleaned["author_user_id"] = None
        else:
            from django.contrib.auth import get_user_model
            from django.core.exceptions import ValidationError

            User = get_user_model()
            try:
                User.objects.get(id=author_user_id)
            except (User.DoesNotExist, ValueError, ValidationError):
                errors["author_user_id"] = "User not found"
            else:
                cleaned["author_user_id"] = author_user_id

    if "author_name" in data:
        cleaned["author_name"] = author_name[:120] if author_name else ""

    # Cross-field: at least one author source must be present. On create there
    # is no existing row, so this is fully decided by the submitted data. On
    # update, the merged (existing + patch) result is checked by the caller
    # (BlogPostService.update_post) once it has the current post loaded.
    if not is_update:
        final_user = cleaned.get("author_user_id")
        final_name = cleaned.get("author_name", "")
        if not final_user and not final_name:
            errors["author"] = "Either author_user_id or author_name is required"

    # -- status --
    if "status" in data or not is_update:
        status = str(data.get("status", BlogPost.STATUS_DRAFT) or "").strip().lower()
        if status not in dict(BlogPost.STATUS_CHOICES):
            errors["status"] = f"Invalid status. Must be one of: {', '.join(dict(BlogPost.STATUS_CHOICES).keys())}"
        else:
            cleaned["status"] = status

    # -- is_featured --
    if "is_featured" in data:
        val = data["is_featured"]
        if isinstance(val, bool):
            cleaned["is_featured"] = val
        elif isinstance(val, str):
            cleaned["is_featured"] = val.lower() in ("true", "1", "yes")
        else:
            cleaned["is_featured"] = bool(val)

    # -- meta fields --
    if "meta_title" in data:
        cleaned["meta_title"] = str(data.get("meta_title", "") or "")[:200]
    if "meta_description" in data:
        cleaned["meta_description"] = str(data.get("meta_description", "") or "")[:500]

    if errors:
        return None, errors
    return cleaned, None


def validate_bulk_action(data: Dict[str, Any]) -> Tuple[Optional[Dict], Optional[Dict]]:
    """Validate blog post bulk action request."""
    errors: Dict[str, str] = {}
    cleaned: Dict[str, Any] = {}

    action = data.get("action")
    valid_actions = ["publish", "archive", "delete"]

    if not action:
        errors["action"] = "This field is required"
    elif action not in valid_actions:
        errors["action"] = f"Invalid action. Must be one of: {', '.join(valid_actions)}"
    else:
        cleaned["action"] = action

    post_ids = data.get("post_ids", [])
    if not post_ids:
        errors["post_ids"] = "At least one post ID is required"
    elif not isinstance(post_ids, list):
        errors["post_ids"] = "Must be a list of post IDs"
    else:
        cleaned["post_ids"] = post_ids

    if errors:
        return None, errors
    return cleaned, None


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------

def serialize_post(post: BlogPost, is_admin: bool = False) -> Dict[str, Any]:
    """Serialize a single blog post."""
    data: Dict[str, Any] = {
        "id": str(post.id),
        "title": post.title,
        "slug": post.slug,
        "excerpt": post.excerpt,
        "content": post.content,
        "cover_image_url": post.cover_image_url,
        "category": {
            "id": str(post.category.id),
            "name": post.category.name,
            "slug": post.category.slug,
        } if post.category else None,
        "author": post.author_display_name,
        "is_featured": post.is_featured,
        "published_at": post.published_at.isoformat() if post.published_at else None,
        "meta_title": post.meta_title,
        "meta_description": post.meta_description,
        "created_at": post.created_at.isoformat() if post.created_at else None,
        "updated_at": post.updated_at.isoformat() if post.updated_at else None,
    }

    if is_admin:
        data["status"] = post.status
        data["author_user_id"] = str(post.author_user_id) if post.author_user_id else None
        data["author_name"] = post.author_name

    return data


def serialize_post_list(
    posts: List[BlogPost], is_admin: bool = False
) -> List[Dict[str, Any]]:
    """Serialize a list of blog posts."""
    return [serialize_post(p, is_admin) for p in posts]


def serialize_bulk_action_result(results: Dict) -> Dict:
    """Serialize bulk action result for API response."""
    return {
        "success": [
            {"id": item["id"], "title": item.get("title", item["id"])}
            for item in results.get("success", [])
        ],
        "failed": [
            {"id": item["id"], "title": item.get("title", item["id"]), "reason": item["reason"]}
            for item in results.get("failed", [])
        ],
        "total": results.get("total", 0),
        "success_count": len(results.get("success", [])),
        "failed_count": len(results.get("failed", [])),
    }
