# Generated by Django 4.2.11 on 2026-07-12 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'blog category',
                'verbose_name_plural': 'blog categories',
                'db_table': 'blog_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='excerpt')),
                ('content', models.TextField(verbose_name='content')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, verbose_name='cover image URL')),
                ('author_name', models.CharField(blank=True, help_text='Used when the author is not a registered user.', max_length=120, verbose_name='author name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='featured')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='author user')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'db_table': 'blog_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug'], name='blog_catego_slug_ca79bd_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_posts_slug_b4ca25_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_at'], name='blog_posts_status_d9ff7c_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_featured', '-published_at'], name='blog_posts_is_feat_c22a48_idx'),
        ),
    ]
