# Generated by Django 4.2.11 on 2026-05-31 11:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_productvariant_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('bundle_price', models.DecimalField(decimal_places=2, help_text='Discounted price for the entire bundle', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='bundle price')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ends at')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'promotion',
                'verbose_name_plural': 'promotions',
                'db_table': 'promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='promotions/%Y/%m/', verbose_name='image')),
                ('image_type', models.CharField(choices=[('banner', 'Banner'), ('thumbnail', 'Thumbnail'), ('gallery', 'Gallery')], default='gallery', max_length=20, verbose_name='image type')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='promotions.promotion')),
            ],
            options={
                'verbose_name': 'promotion image',
                'verbose_name_plural': 'promotion images',
                'db_table': 'promotion_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Price at promotion creation time', max_digits=10, verbose_name='original price')),
                ('cost_price_snapshot', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price at promotion creation time for profit calculation', max_digits=10, verbose_name='cost price snapshot')),
                ('is_free', models.BooleanField(default=False, help_text='Item is given for free (counts toward bundle but no cost)', verbose_name='free item')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.promotion')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'promotion item',
                'verbose_name_plural': 'promotion items',
                'db_table': 'promotion_items',
                'indexes': [models.Index(fields=['promotion', 'variant'], name='promotion_i_promoti_7f3452_idx'), models.Index(fields=['is_available'], name='promotion_i_is_avai_31e03a_idx')],
                'unique_together': {('promotion', 'variant')},
            },
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['slug'], name='promotions_slug_58a228_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='promotions_status_1c63fb_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['created_at'], name='promotions_created_13f13d_idx'),
        ),
    ]
