# Generated by Django 4.2.11 on 2026-07-04 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customerprofile_date_of_birth'),
        ('orders', '0012_order_affiliate_order_affiliate_commission_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='discount type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='value')),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum subtotal')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maximum discount amount')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ends at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_codes', to='users.affiliate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'discount code',
                'verbose_name_plural': 'discount codes',
                'db_table': 'discount_codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='commission rate')),
                ('commissionable_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='commissionable amount')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='commission amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accrued', 'Accrued'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('accrued_at', models.DateTimeField(blank=True, null=True, verbose_name='accrued at')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversed at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='users.affiliate')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='promotions.discountcode')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commission', to='orders.order')),
            ],
            options={
                'verbose_name': 'affiliate commission',
                'verbose_name_plural': 'affiliate commissions',
                'db_table': 'affiliate_commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['code'], name='discount_co_code_085c69_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='discount_co_is_acti_97887a_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['affiliate'], name='discount_co_affilia_a6ef20_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['affiliate', 'status'], name='affiliate_c_affilia_dfeb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatecommission',
            index=models.Index(fields=['order'], name='affiliate_c_order_i_237c53_idx'),
        ),
    ]
