# Generated by Django 4.2.11 on 2026-05-30 15:46

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(db_index=True, max_length=50, verbose_name='app name')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='action')),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=20, verbose_name='severity')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='description')),
                ('status_code', models.IntegerField(db_index=True, verbose_name='status code')),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='user id')),
                ('user_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='user email')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='request path')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='HTTP method')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'system log',
                'verbose_name_plural': 'system logs',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_name', 'created_at'], name='system_logs_app_nam_f854dc_idx'), models.Index(fields=['severity', 'created_at'], name='system_logs_severit_5c9f81_idx'), models.Index(fields=['user_id', 'created_at'], name='system_logs_user_id_9ba726_idx'), models.Index(fields=['action', 'created_at'], name='system_logs_action_bb3eda_idx'), models.Index(fields=['status_code', 'created_at'], name='system_logs_status__79db34_idx'), models.Index(fields=['app_name', 'action', 'severity'], name='system_logs_app_nam_67e0a7_idx'), models.Index(fields=['created_at'], name='system_logs_created_2e006d_idx')],
            },
        ),
    ]
