# Generated by Django 4.2.11 on 2026-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='request path'),
        ),
    ]
