# Generated by Django 4.2.11 on 2026-05-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_systemlog_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HTTP method'),
        ),
    ]
