# Generated by Django 4.2.11 on 2026-07-10 21:32

import apps.common.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_systemlog_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('paystack_enabled', models.BooleanField(default=True, verbose_name='Paystack enabled')),
                ('pod_enabled', models.BooleanField(default=True, verbose_name='Pay on Delivery enabled')),
                ('default_payment_method', models.CharField(default='paystack', max_length=20, verbose_name='default payment method')),
                ('pod_max_order_value', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='POD max order value')),
                ('pod_max_quantity', models.PositiveIntegerField(default=10, verbose_name='POD max quantity')),
                ('paystack_min_amount', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Paystack min amount')),
                ('paystack_max_amount', models.DecimalField(decimal_places=2, default=Decimal('999999.99'), max_digits=10, verbose_name='Paystack max amount')),
                ('notifications', models.JSONField(default=apps.common.models.default_notifications, verbose_name='notifications')),
                ('guest_checkout_enabled', models.BooleanField(default=True, verbose_name='guest checkout enabled')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='minimum order value')),
                ('order_number_prefix', models.CharField(default='ORD', max_length=10, verbose_name='order number prefix')),
                ('auto_cancel_unpaid_hours', models.PositiveIntegerField(default=0, verbose_name='auto-cancel unpaid after (hours)')),
                ('store_name', models.CharField(blank=True, max_length=100, verbose_name='store name')),
                ('support_email', models.CharField(blank=True, max_length=255, verbose_name='support email')),
                ('support_phone', models.CharField(blank=True, max_length=30, verbose_name='support phone')),
                ('currency', models.CharField(default='GHS', max_length=3, verbose_name='currency')),
                ('store_country', models.CharField(blank=True, max_length=2, verbose_name='store country')),
                ('store_state', models.CharField(blank=True, max_length=80, verbose_name='store state/region')),
                ('store_city', models.CharField(blank=True, max_length=80, verbose_name='store city')),
                ('store_postal_code', models.CharField(blank=True, max_length=20, verbose_name='store postal code')),
                ('store_address', models.CharField(blank=True, max_length=255, verbose_name='store address')),
                ('default_low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='default low-stock threshold')),
                ('hide_out_of_stock', models.BooleanField(default=False, verbose_name='hide out-of-stock products')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='tax rate (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'general config',
                'verbose_name_plural': 'general config',
                'db_table': 'general_config',
            },
        ),
    ]
