# Generated by Django 4.2.11 on 2026-07-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_generalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfig',
            name='tax_inclusive',
            field=models.BooleanField(default=False, verbose_name='tax included in product prices'),
        ),
    ]
