# Generated by Django 4.2.11 on 2025-12-27 18:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='email verified at'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2012, 12, 27), message='Must be at least 13 years old.')], verbose_name='date of birth'),
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='token')),
                ('token_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('account_activation', 'Account Activation')], default='email_verification', max_length=20, verbose_name='token type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='is used')),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='used at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification token',
                'verbose_name_plural': 'verification tokens',
                'db_table': 'verification_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_used'], name='verificatio_token_a3c0ae_idx'), models.Index(fields=['user', 'token_type'], name='verificatio_user_id_acad48_idx'), models.Index(fields=['expires_at', 'is_used'], name='verificatio_expires_8882fd_idx'), models.Index(fields=['created_at'], name='verificatio_created_209e91_idx')],
            },
        ),
    ]
