# Generated by Django 4.2.11 on 2025-12-28 01:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationtoken',
            name='additional_data',
            field=models.JSONField(blank=True, help_text='Additional data like IP for password reset', null=True, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2012, 12, 28), message='Must be at least 13 years old.')], verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token_type',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('account_activation', 'Account Activation'), ('password_reset', 'Password Reset')], default='email_verification', max_length=20, verbose_name='token type'),
        ),
        migrations.AddIndex(
            model_name='verificationtoken',
            index=models.Index(fields=['token_type', 'is_used', 'expires_at'], name='verificatio_token_t_2ed7d7_idx'),
        ),
    ]
