# Generated by Django 4.2.11 on 2026-01-03 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customerprofile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_1',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='address_line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='bernard@gmail.com', max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='Bernard', max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='Kusi', max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=233592724409, max_length=20, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping Address'), ('billing', 'Billing Address')], default='shipping', max_length=20, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='instructions',
            field=models.TextField(blank=True, verbose_name='delivery instructions'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, verbose_name='state/province'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
