# Generated by Django 4.2.11 on 2026-05-24 11:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_affiliate',
            field=models.BooleanField(default=False, help_text='Designates whether the user is an affiliate marketer.', verbose_name='affiliate'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a guest (no password set).', verbose_name='guest'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2013, 5, 24), message='Must be at least 13 years old.')], verbose_name='date of birth'),
        ),
    ]
