# Generated by Django 4.2.11 on 2026-05-24 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_is_affiliate_user_is_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_affiliate',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether the user is a guest (no password set).', verbose_name='guest'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['email'], name='addresses_email_57e321_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_guest'], name='users_is_gues_12f373_idx'),
        ),
    ]
