# Generated by Django 4.2.11 on 2026-05-24 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_is_affiliate_alter_address_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='referral code')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total earnings')),
                ('pending_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='pending earnings')),
                ('paid_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='paid earnings')),
                ('total_referrals', models.PositiveIntegerField(default=0, verbose_name='total referrals')),
                ('active_referrals', models.PositiveIntegerField(default=0, verbose_name='active referrals')),
                ('level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20, verbose_name='affiliate level')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=2.0, help_text='Commission percentage for this affiliate', max_digits=5, verbose_name='commission rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_payout_at', models.DateTimeField(blank=True, null=True, verbose_name='last payout at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'affiliate',
                'verbose_name_plural': 'affiliates',
                'db_table': 'affiliates',
                'ordering': ['-total_earnings'],
                'indexes': [models.Index(fields=['referral_code'], name='affiliates_referra_367e51_idx'), models.Index(fields=['is_active'], name='affiliates_is_acti_401be7_idx'), models.Index(fields=['level'], name='affiliates_level_474b4b_idx'), models.Index(fields=['total_earnings'], name='affiliates_total_e_0cbb4f_idx')],
            },
        ),
    ]
