# Generated by Django 4.2.11 on 2026-07-08 18:58

import apps.users.models.customer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[apps.users.models.customer.validate_minimum_age], verbose_name='date of birth'),
        ),
    ]
