# Generated by Django 4.2.11 on 2026-07-05 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('preheader', models.CharField(blank=True, max_length=255, verbose_name='preheader')),
                ('html_body', models.TextField(verbose_name='HTML body')),
                ('text_body', models.TextField(blank=True, verbose_name='text body')),
                ('campaign_type', models.CharField(choices=[('newsletter', 'Newsletter'), ('promotion', 'Promotion'), ('announcement', 'Announcement'), ('custom', 'Custom')], db_index=True, default='custom', max_length=20, verbose_name='campaign type')),
                ('segment', models.CharField(choices=[('all_users', 'All Users'), ('customers', 'Customers'), ('verified_customers', 'Verified Customers'), ('affiliates', 'Affiliates'), ('newsletter_subscribers', 'Newsletter Subscribers'), ('marketing_optin', 'Marketing Opt-in')], default='all_users', max_length=30, verbose_name='segment')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('partially_sent', 'Partially Sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='total recipients')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='sent count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='failed count')),
                ('error_sample', models.JSONField(blank=True, default=list, verbose_name='error sample')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email campaign',
                'verbose_name_plural': 'email campaigns',
                'db_table': 'email_campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='email_campa_status_5afa58_idx'), models.Index(fields=['campaign_type'], name='email_campa_campaig_c4fa52_idx')],
            },
        ),
    ]
