# Generated by Django 4.2.11 on 2026-01-03 00:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_alter_customerprofile_date_of_birth'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='guest email')),
                ('guest_first_name', models.CharField(blank=True, max_length=50, verbose_name='guest first name')),
                ('guest_last_name', models.CharField(blank=True, max_length=50, verbose_name='guest last name')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='guest phone')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='payment status')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20, verbose_name='payment method')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='shipping cost')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tax amount')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='tax rate')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount amount')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('shipping_method', models.CharField(blank=True, max_length=100, verbose_name='shipping method')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='carrier')),
                ('payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='payment intent id')),
                ('payment_receipt_url', models.URLField(blank=True, max_length=500, verbose_name='payment receipt url')),
                ('customer_note', models.TextField(blank=True, verbose_name='customer note')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('email_sent', models.BooleanField(default=False, verbose_name='confirmation email sent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='shipped at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_orders', to='users.address', verbose_name='billing address')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipping_orders', to='users.address', verbose_name='shipping address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200, verbose_name='product title')),
                ('product_slug', models.SlugField(max_length=200, verbose_name='product slug')),
                ('variant_attributes', models.JSONField(default=dict, verbose_name='variant attributes')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='discount amount')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'db_table': 'order_items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order', 'sku'], name='order_items_order_i_be4219_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_payment_050188_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_user_id_51663a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['guest_email'], name='orders_guest_e_894bb5_idx'),
        ),
    ]
