# Generated by Django 4.2.11 on 2026-07-09 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('product', 'Product'), ('promotion', 'Promotion')], db_index=True, default='manual', max_length=20, verbose_name='source')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='source object id')),
                ('caption', models.TextField(verbose_name='caption')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='image URL')),
                ('platforms', models.JSONField(blank=True, default=list, verbose_name='platforms')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending_approval', max_length=20, verbose_name='status')),
                ('zernio_post_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Zernio post id')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='scheduled for')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='error')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social post',
                'verbose_name_plural': 'social posts',
                'db_table': 'social_posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'object_id'], name='social_post_source_e532eb_idx'), models.Index(fields=['status', 'created_at'], name='social_post_status_07bcd6_idx')],
            },
        ),
    ]
