# Generated by Django 4.2.11 on 2026-07-09 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zernio_post_id', models.CharField(db_index=True, max_length=100, verbose_name='post id')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('message', models.TextField(verbose_name='message')),
                ('is_reply', models.BooleanField(default=False, verbose_name='is admin reply')),
                ('hidden', models.BooleanField(default=False, verbose_name='hidden')),
                ('liked', models.BooleanField(default=False, verbose_name='liked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'db_table': 'social_sandbox_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SandboxConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('platform', models.CharField(max_length=30, verbose_name='platform')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'db_table': 'social_sandbox_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='live', max_length=10, verbose_name='mode')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'social config',
                'verbose_name_plural': 'social config',
                'db_table': 'social_config',
            },
        ),
        migrations.CreateModel(
            name='SandboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='message')),
                ('is_outgoing', models.BooleanField(default=False, verbose_name='outgoing')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.sandboxconversation')),
            ],
            options={
                'db_table': 'social_sandbox_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
