# Generated by Django 4.2.11 on 2026-07-09 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_sandboxcomment_sandboxconversation_socialconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'db_table': 'social_sandbox_profiles',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SandboxAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30, verbose_name='platform')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='social.sandboxprofile')),
            ],
            options={
                'db_table': 'social_sandbox_accounts',
                'ordering': ['created_at'],
            },
        ),
    ]
