# Generated by Django 4.2.11 on 2026-07-09 22:54

import apps.social.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_sandboxprofile_sandboxaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, storage=apps.social.models._social_media_storage, upload_to='social/%Y/%m/', verbose_name='file')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], db_index=True, default='image', max_length=10, verbose_name='media type')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social media file',
                'verbose_name_plural': 'social media files',
                'db_table': 'social_media_library',
                'ordering': ['-created_at'],
            },
        ),
    ]
