# Generated by Codex on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='media_items',
            field=models.JSONField(blank=True, default=list, verbose_name='media items'),
        ),
    ]
